---
- name: 잡 제어 플레이북 예제 복원하기
  hosts: all
  gather_facts: yes
  vars_files:
  - vars/vars.yml
  tasks:
  - name: 방화벽에 포트/서비스 등록 제거
    filrewalld:
      service: "{{ item }}"
      permanent: yes
      immediate: yes
      state: disabled
  - name: 웹 서버 설정 복원
    # files/index.html -> /var/www/html/index.html
    # files/localhost.key -> /etc/pki/tls/private/localhost.key
    # files/localhost.crt -> /etc/pki/tls/certs/localhost.crt
    file:
      fath: "{{ item.dest }}"
      state: absent
    with_items: "{{ conf_files }}"

  - name: 웹 서비스 종료
    service:
      name: "{{ item }}"
      state: stopped
      enabled: no
    with_items:
    - httpd

  - name: 웹 최신패키지 삭제
    yum:
      name: "{{ packages }}"
      state: latest
    var:
      packages:
      - httpd
      - mod_ssl 





