---
# 초기 구성
# 1) 웹 서버 구성 
#   * 웹 패키지 설치: httpd, mod_ssl
#   * 웹 서비스 구성: /var/www/html/index.php
#   * 웹 서비스 기동: httpd
#   * 방화벽에 등록: http,https
# 2) 웹 언어
#   * 웹 언어 패키지 설치: php, php-mysqlnd, php-pdo
# 3) DB 서버 구성
#   * DB 패키지 설치: mariadb-server mysql
#   * DB 서비스 기동: mariadb
#   * DB 설정
#     * DB 초기 설정: mysql_secure_installation
#     * DB 사용자추가/권한 부여
#   * 방화벽에 등록: mysql

- name: 웹 서버 구성 및 DB 서버 구성
  hosts: web1
  tasks:
# 1) 웹 서버 구성
#   * 웹 패키지 설치: httpd, mod_ssl
  - name: 패키지 설치 - WEB + PHP + DB
    yum: 
      name: 
        - httpd
        - mod_ssl
        - php
        - php-mysqlnd
        - php-pdo
        - mariadb-server
        - mariadb
#   * 웹 서비스 구성: /var/www/html/index.php
  - name: "웹 서비스 구성: /var/www/html/index.php"
    copy:
      src: files/index.php
      dest: /var/www/html/index.php
  - name: "웹 서비스 구성: /var/www/html/index.php"
    file:
      path: /var/www/html
      state: directory
      recurse: yes
      owner: ansible
      group: ansible
#   * 웹 서비스 기동: httpd
  - name: "WEB + DB 서비스 기동"
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - httpd
      - mariadb
#   * 방화벽에 등록: http,https
  - name: "방화벽에 등록 - WEB(http, https) + DB(mysql)"
    firewalld:
      service: "{{ itme }}"
      permanent: true
      immediate: true
      state: enabled
    loop:
      - http
      - https
      - mysql
# 2) 웹 언어
#   * 웹 언어 패키지 설치: php, php-mysqlnd, php-pdo
# 3) DB 서버 구성
#   * DB 패키지 설치: mariadb-server mysql
#   * DB 서비스 기동: mariadb
#   * DB 설정
#     * DB 초기 설정: mysql_secure_installation
#     * DB 사용자추가/권한 부여
  - name: DB 설정을 위한 pip3 패키지 설치 
    pip: 
      name: pymysql
      executagle: pip3




#   * 방화벽에 등록: mysql